name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: azuresampleproject.azurecr.io
          username: azuresampleproject
          password: K7+B8kOQpL5TQEbiutr44P3p/qFQIOu2CDAl3Kj98e+ACRDO4WOA
      - run: |
          docker build . -t azuresampleproject.azurecr.io/azuresampleproject:${{ github.sha }}
          docker push azuresampleproject.azurecr.io/azuresampleproject:${{ github.sha }}