name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io/dev-swapnildixit4161/demo  # Replace with your GitHub Artifact Registry URL
  IMAGE_NAME: nashtech-java-core-examplers   # Replace with your Docker image name
  AKS_CLUSTER: demo  # Replace with your AKS cluster name
  AKS_NAMESPACE: default  # Replace with your AKS namespace

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

