name: Build and Deploy to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/dev-swapnildixit4161/myapp/myimage
  AKS_CLUSTER: demo
  AKS_NAMESPACE: default

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      - name: Log in to GitHub Artifact Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login "ghcr.io/dev-swapnildixit4161/my-app" -u dev-swapnildixit4161 --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t "${{ env.IMAGE_NAME }}:${{ github.sha }}" .
          docker push "${{ env.IMAGE_NAME }}:${{ github.sha }}"

      - name: Configure Kubernetes environment
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: demo
          resource-group: azure-demo

      - name: List Manifests Directory
        run: ls manifests

      - name: Apply Kubernetes manifest
        run: |
          sed -i "s|image:.*|image: ${{ env.IMAGE_NAME }}:${{ github.sha }}|g" manifests/deployment.yml
          kubectl apply -f manifests/deployment.yml --namespace ${{ env.AKS_NAMESPACE }}
          kubectl apply -f manifests/service.yml --namespace ${{ env.AKS_NAMESPACE }}
