name: Build and Deploy to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/dev-swapnildixit4161/my-app
  IMAGE_NAME: my-app
  AKS_CLUSTER: demo
  AKS_NAMESPACE: default

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
            context: .
            push: true
            tags: ghcr.io/dev-swapnildixit4161/my-app:${{ github.sha }}
        env:
            CR_PAT: ${{ secrets.GITHUB_TOKEN }}



      - name: Configure Kubernetes environment
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: demo
          resource-group: azure-demo



      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
          
