name: Build and Deploy to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/dev-swapnildixit4161/my-app:latest
  IMAGE_NAME: my-app
  AKS_CLUSTER: demo
  AKS_NAMESPACE: default

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Log in to GitHub Artifact Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login "${{ env.REGISTRY }}" -u dev-swapnildixit4161 --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" .
          docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"

      - name: Deploy to AKS
        run: |
          az aks set-context --name ${{ env.AKS_CLUSTER }} --resource-group azure-demo
          az aks get-credentials --name ${{ env.AKS_CLUSTER }} --resource-group azure-demo --overwrite-existing

      - name: Apply Kubernetes manifest
        run: |
          kubectl apply -f path/to/manifests/deployment.yaml --namespace ${{ env.AKS_NAMESPACE }}
          kubectl apply -f path/to/manifests/service.yaml --namespace ${{ env.AKS_NAMESPACE }}
